CREATE USER WEBAPP IDENTIFIED BY SuperSecretMyPassword123;
GRANT CREATE SESSION TO WEBAPP;

SELECT username, authentication_type
FROM dba_users WHERE username='WEBAPP';

ALTER USER WEBAPP
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP;